apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jqw1fmptd-nodejs 
  janus-idp.io/tekton: jqw1fmptd-nodejs
  backstage.io/kubernetes-id: jqw1fmptd-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jqw1fmptd-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml